dist: bionic

before_install:
  - npm i -g npm@latest

env:
  global:
    - CC_TEST_REPORTER_ID=46a1a68240d4dfbad17c616265ab33a938d4d12c420e2a2e2f0f7a4427f5187c

language: node_js
node_js:
  - "10.16.0"
cache:
  npm: false

branches:
  only:
    - master

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - npm run coverage
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT